name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Setup JSON fixtures
        run: |
          cp cypress/fixtures/users.json.example cypress/fixtures/users.json
          cp cypress/fixtures/bankAccount.json.example cypress/fixtures/bankAccount.json
          cp cypress/fixtures/accountUsers.json.example cypress/fixtures/accountUsers.json

      - name: Build and Start App
        run: |
          npm run dev &
          npx wait-on http://localhost:3000

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:3000'